services:
  web:
    restart: always
    build: .
    image: namanyash/sit737-5.1p
    ports:
      - "8080:5000"
    healthcheck:
      test: curl --fail http://localhost:5000/health || exit 1
      interval: 40s
      timeout: 30s
      retries: 3
      start_period: 60s
